/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2013, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.jboss.test.ws.jaxws.bp20.complexdoc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.8.0-SNAPSHOT (1451528)
 * 2013-05-27T14:31:23.642+08:00
 * Generated source version: 2.8.0-SNAPSHOT
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IComplexDataTypesDocLitW")
@XmlSeeAlso({ObjectFactory.class})
public interface IComplexDataTypesDocLitW {

    @WebResult(name = "RetArrayInt1DResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayInt1D", output = "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayInt1DResponse")
    @RequestWrapper(localName = "RetArrayInt1D", targetNamespace = "http://tempuri.org/", className = "org.jboss.test.ws.jaxws.bp12.complexdoc.RetArrayInt1D")
    @WebMethod(operationName = "RetArrayInt1D", action = "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayInt1D")
    @ResponseWrapper(localName = "RetArrayInt1DResponse", targetNamespace = "http://tempuri.org/", className = "org.jboss.test.ws.jaxws.bp12.complexdoc.RetArrayInt1DResponse")
    public org.jboss.test.ws.jaxws.bp20.complexdoc.IntArray retArrayInt1D(
        @WebParam(name = "inArrayInt1D", targetNamespace = "http://tempuri.org/")
        org.jboss.test.ws.jaxws.bp20.complexdoc.IntArray inArrayInt1D
    );

    @WebResult(name = "RetArrayString1DResult", targetNamespace = "http://tempuri.org/")
    @Action(input = "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayString1D", output = "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayString1DResponse")
    @RequestWrapper(localName = "RetArrayString1D", targetNamespace = "http://tempuri.org/", className = "org.jboss.test.ws.jaxws.bp12.complexdoc.RetArrayString1D")
    @WebMethod(operationName = "RetArrayString1D", action = "http://tempuri.org/IComplexDataTypesDocLitW/RetArrayString1D")
    @ResponseWrapper(localName = "RetArrayString1DResponse", targetNamespace = "http://tempuri.org/", className = "org.jboss.test.ws.jaxws.bp12.complexdoc.RetArrayString1DResponse")
    public org.jboss.test.ws.jaxws.bp20.complexdoc.StringArray retArrayString1D(
        @WebParam(name = "inArrayString1D", targetNamespace = "http://tempuri.org/")
        org.jboss.test.ws.jaxws.bp20.complexdoc.StringArray inArrayString1D
    );
}
